name: Cypress Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # first, install dependencies and Cypress
      # from the root folder using the lock file
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # now run the tests from the subfolder
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false start: 
          start: npm --version